"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Resolver = exports.EnumerableResolver = exports.SpyResolver = exports.NameResolver = exports.RelativeFSResolver = exports.FSResolver = exports.NPMResolver = exports.URLResolver = exports.FallthroughResolver = void 0;
var fallthrough_resolver_1 = require("./resolvers/fallthrough_resolver");
Object.defineProperty(exports, "FallthroughResolver", { enumerable: true, get: function () { return fallthrough_resolver_1.FallthroughResolver; } });
var url_resolver_1 = require("./resolvers/url_resolver");
Object.defineProperty(exports, "URLResolver", { enumerable: true, get: function () { return url_resolver_1.URLResolver; } });
var npm_resolver_1 = require("./resolvers/npm_resolver");
Object.defineProperty(exports, "NPMResolver", { enumerable: true, get: function () { return npm_resolver_1.NPMResolver; } });
var fs_resolver_1 = require("./resolvers/fs_resolver");
Object.defineProperty(exports, "FSResolver", { enumerable: true, get: function () { return fs_resolver_1.FSResolver; } });
var relative_fs_resolver_1 = require("./resolvers/relative_fs_resolver");
Object.defineProperty(exports, "RelativeFSResolver", { enumerable: true, get: function () { return relative_fs_resolver_1.RelativeFSResolver; } });
var name_resolver_1 = require("./resolvers/name_resolver");
Object.defineProperty(exports, "NameResolver", { enumerable: true, get: function () { return name_resolver_1.NameResolver; } });
var spy_resolver_1 = require("./resolvers/spy_resolver");
Object.defineProperty(exports, "SpyResolver", { enumerable: true, get: function () { return spy_resolver_1.SpyResolver; } });
var enumerable_resolver_1 = require("./resolvers/enumerable_resolver");
Object.defineProperty(exports, "EnumerableResolver", { enumerable: true, get: function () { return enumerable_resolver_1.EnumerableResolver; } });
var resolver_1 = require("./resolvers/resolver");
Object.defineProperty(exports, "Resolver", { enumerable: true, get: function () { return resolver_1.Resolver; } });
//# sourceMappingURL=index.js.map